apiVersion: v1
kind: Secret
metadata:
  name: ecr-secret
  namespace: test-cluster-namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIyMjQwMzk4OTYwNjcuZGtyLmVjci5hcC1zb3V0aC0xLmFtYXpvbmF3cy5jb20iOiB7fSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfSwKCQkiYWkiOiB7CgkJCSJob29rcyI6ICJidWlsZCxidWlsZHggYnVpbGQscnVuLGNvbXBvc2UiCgkJfSwKCQkiY29tcG9zZSI6IHsKCQkJImhvb2tzIjogImxvZ3MsY29tcG9zZSBsb2dzLGNvbXBvc2UgYXR0YWNoLGNvbXBvc2UgdXAiCgkJfSwKCQkiZGVidWciOiB7CgkJCSJob29rcyI6ICJleGVjIgoJCX0sCgkJInNjb3V0IjogewoJCQkiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCgkJfQoJfSwKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
